version: '3'

services:
    db:
        image: postgres:10.1-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: db_password123
            POSTGRES_USER: postgres
            POSGTRES_DB: postgres
    web:
        build: .
        working_dir: /app/petition_service
        command: gunicorn -w 4 petition_service.wsgi:application --bind 0.0.0.0:443 --keyfile /app/certs/ssl.key --certfile /app/certs/ssl.crt
        volumes:
            - .:/app
        ports:
            - "443:443"
        environment:
            - "DEBUG=1"
        depends_on:
            - db

volumes:
    postgres_data: