# Generated by Django 3.2.3 on 2021-06-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210525_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Petition'),
        ),
    ]
